"""initial schema

Revision ID: 00661ccbdc35
Revises: 
Create Date: 2026-08-22 22:15:34.765686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '00661ccbdc35'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_definition',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('spec', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('version >= 1', name='ck_workflow_definition_version_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_definition_key'), 'workflow_definition', ['key'], unique=True)
    op.create_table('schedule',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('definition_id', sa.UUID(), nullable=False),
    sa.Column('cron', sa.Text(), nullable=False),
    sa.Column('timezone', sa.Text(), server_default=sa.text("'UTC'"), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_fired_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('next_fire_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['definition_id'], ['workflow_definition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_run',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('definition_id', sa.UUID(), nullable=False),
    sa.Column('definition_key', sa.Text(), nullable=False),
    sa.Column('spec_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'succeeded', 'failed', 'cancelled', name='workflow_status'), nullable=False),
    sa.Column('trigger_type', sa.Enum('manual', 'scheduled', 'api', name='trigger_type'), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('idempotency_key', sa.Text(), nullable=True),
    sa.Column('queued_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['definition_id'], ['workflow_definition.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_workflow_run_definition_key_created_at', 'workflow_run', ['definition_key', 'created_at'], unique=False)
    op.create_index('ix_workflow_run_status_created_at', 'workflow_run', ['status', 'created_at'], unique=False)
    op.create_table('schedule_fire',
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_for', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_run.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], ),
    sa.PrimaryKeyConstraint('schedule_id', 'scheduled_for')
    )
    op.create_table('task_run',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('task_key', sa.Text(), nullable=False),
    sa.Column('handler', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'queued', 'running', 'retrying', 'succeeded', 'failed', 'upstream_failed', 'cancelled', name='task_status'), nullable=False),
    sa.Column('depends_on', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('queued_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('dispatch_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('lease_expires_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_type', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'task_key', name='uq_task_run_run_id_task_key')
    )
    op.create_index('ix_task_run_run_id_status', 'task_run', ['run_id', 'status'], unique=False)
    op.create_index('ix_task_run_status_lease_expires_at', 'task_run', ['status', 'lease_expires_at'], unique=False)
    op.create_index('ix_task_run_status_next_attempt_at', 'task_run', ['status', 'next_attempt_at'], unique=False)
    op.create_index('ix_task_run_status_queued_at', 'task_run', ['status', 'queued_at'], unique=False)
    op.create_table('task_attempt',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_run_id', sa.UUID(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('running', 'succeeded', 'failed', name='attempt_status'), nullable=False),
    sa.Column('worker_id', sa.Text(), nullable=False),
    sa.Column('celery_task_id', sa.Text(), nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_type', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.Column('logs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['task_run_id'], ['task_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_run_id', 'attempt_number', name='uq_task_attempt_task_run_id_attempt_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_attempt')
    op.drop_index('ix_task_run_status_queued_at', table_name='task_run')
    op.drop_index('ix_task_run_status_next_attempt_at', table_name='task_run')
    op.drop_index('ix_task_run_status_lease_expires_at', table_name='task_run')
    op.drop_index('ix_task_run_run_id_status', table_name='task_run')
    op.drop_table('task_run')
    op.drop_table('schedule_fire')
    op.drop_index('ix_workflow_run_status_created_at', table_name='workflow_run')
    op.drop_index('ix_workflow_run_definition_key_created_at', table_name='workflow_run')
    op.drop_table('workflow_run')
    op.drop_table('schedule')
    op.drop_index(op.f('ix_workflow_definition_key'), table_name='workflow_definition')
    op.drop_table('workflow_definition')
    # ### end Alembic commands ###

    # Autogenerate does not emit these: a native PostgreSQL enum type is an
    # independent object that outlives the tables whose columns used it, so
    # dropping the tables above leaves 'task_status', 'attempt_status', etc.
    # orphaned. Without this, a subsequent upgrade fails with
    # "type ... already exists" — verified by actually running
    # upgrade -> downgrade -> upgrade during M1 validation.
    sa.Enum(name="task_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="attempt_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="workflow_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="trigger_type").drop(op.get_bind(), checkfirst=True)
